services:
  nextjs:
    build: ./
    container_name: nextjs
    networks:
      - host
    ports:
      - "3000:3000"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - nextjs
