services:
  nextjs:
    build: .
    container_name: nextjs
    ports:
      - "3000:3000"
    env_file:
      - /var/www/app_config/.env

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - nextjs
