services:
  # PostgreSQL データベース (最低限の設定)
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - traubling-network

  # Go バックエンド
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://appuser:secretpass@db:5432/appdb?sslmode=disable
      - PORT=8080
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - traubling-network

  # Next.js フロントエンド
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - DATABASE_URL=postgresql://appuser:secretpass@db:5432/appdb?sslmode=disable
    ports:
      - '3000:3000'
    depends_on:
      - db
      - backend
    networks:
      - traubling-network

volumes:
  postgres_data:
    driver: local

networks:
  traubling-network:
    driver: bridge
