# version: '3.8'

services:
  # データベース（PostgreSQL）
  # db:
  #   image: postgres:15-alpine
  #   restart: always
  #   environment:
  #     POSTGRES_USER:     appuser
  #     POSTGRES_PASSWORD: secretpass
  #     POSTGRES_DB:       appdb
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'

  # Go バックエンド
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   restart: always
  #   # ローカル開発用にバイナリを直接実行
  #   command: ["./server"]
  #   volumes:
  #     - ./backend:/app
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - db

  # Next.js フロントエンド
  frontend:
    build:
      context: .             # プロジェクトルートをコンテキストに
      dockerfile: Dockerfile # ルート直下の Dockerfile を指定
    restart: always
    command: npm run dev     # npm に置き換え
    volumes:
      - ./:/app
      - /app/node_modules   # ホスト側 node_modules 上書きを防止
    ports:
      - '3000:3000'
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    # environment:
    #   NEXT_PUBLIC_API_URL: http://backend:8080
    # ports:
    #   - '3000:3000'
    # depends_on:
    #   - backend

volumes:
  db_data:
