services:
  # PostgreSQL データベース
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: appdb
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - traubling-dev

  # Go バックエンド (開発用)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://appuser:secretpass@db:5432/appdb?sslmode=disable
      - PORT=8080
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - traubling-dev

  # Next.js フロントエンド (開発用)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - DATABASE_URL=postgresql://appuser:secretpass@db:5432/appdb?sslmode=disable
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - db
      - backend
    networks:
      - traubling-dev

volumes:
  postgres_data_dev:
    driver: local

networks:
  traubling-dev:
    driver: bridge
