version: '3.8'

services:
  # PostgreSQL データベース
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: appdb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - traubling-dev

  # Redis
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data_dev:/data
    networks:
      - traubling-dev

  # Go バックエンド (開発用 - ホットリロード)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://appuser:secretpass@db:5432/appdb?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev-jwt-secret-key
      - PORT=8080
      - GO_ENV=development
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
      - /app/tmp
    depends_on:
      - db
      - redis
    networks:
      - traubling-dev

  # Next.js フロントエンド (開発用 - ホットリロード)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=dev-nextauth-secret
      - WATCHPACK_POLLING=true
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - traubling-dev

  # Adminer (データベース管理ツール)
  adminer:
    image: adminer:4-standalone
    restart: unless-stopped
    ports:
      - '8081:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db
    networks:
      - traubling-dev

  # Mailhog (メール開発用)
  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - '1025:1025'  # SMTP
      - '8025:8025'  # Web UI
    networks:
      - traubling-dev

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  traubling-dev:
    driver: bridge
