apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-traubling
  namespace: web
  labels: { app: web-traubling }
spec:
  replicas: 2
  selector:
    matchLabels: { app: web-traubling }
  template:
    metadata:
      labels: { app: web-traubling }
    spec:
      containers:
        - name: app
         
          image: ghcr.io/kaicyou2532/web_traubling:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"

envFrom:
  - secretRef:
      name: app-env
