export const countries = [
    { code: "AF", name: "Afghanistan", japaneseName: "アフガニスタン" },
    { code: "AL", name: "Albania", japaneseName: "アルバニア" },
    { code: "DZ", name: "Algeria", japaneseName: "アルジェリア" },
    { code: "AD", name: "Andorra", japaneseName: "アンドラ" },
    { code: "AO", name: "Angola", japaneseName: "アンゴラ" },
    { code: "AG", name: "Antigua and Barbuda", japaneseName: "アンティグア・バーブーダ" },
    { code: "AR", name: "Argentina", japaneseName: "アルゼンチン" },
    { code: "AM", name: "Armenia", japaneseName: "アルメニア" },
    { code: "AU", name: "Australia", japaneseName: "オーストラリア" },
    { code: "AT", name: "Austria", japaneseName: "オーストリア" },
    { code: "AZ", name: "Azerbaijan", japaneseName: "アゼルバイジャン" },
    { code: "BS", name: "Bahamas", japaneseName: "バハマ" },
    { code: "BH", name: "Bahrain", japaneseName: "バーレーン" },
    { code: "BD", name: "Bangladesh", japaneseName: "バングラデシュ" },
    { code: "BB", name: "Barbados", japaneseName: "バルバドス" },
    { code: "BY", name: "Belarus", japaneseName: "ベラルーシ" },
    { code: "BE", name: "Belgium", japaneseName: "ベルギー" },
    { code: "BZ", name: "Belize", japaneseName: "ベリーズ" },
    { code: "BJ", name: "Benin", japaneseName: "ベナン" },
    { code: "BT", name: "Bhutan", japaneseName: "ブータン" },
    { code: "BO", name: "Bolivia", japaneseName: "ボリビア" },
    { code: "BA", name: "Bosnia and Herzegovina", japaneseName: "ボスニア・ヘルツェゴビナ" },
    { code: "BW", name: "Botswana", japaneseName: "ボツワナ" },
    { code: "BR", name: "Brazil", japaneseName: "ブラジル" },
    { code: "BN", name: "Brunei Darussalam", japaneseName: "ブルネイ" },
    { code: "BG", name: "Bulgaria", japaneseName: "ブルガリア" },
    { code: "BF", name: "Burkina Faso", japaneseName: "ブルキナファソ" },
    { code: "BI", name: "Burundi", japaneseName: "ブルンジ" },
    { code: "CV", name: "Cabo Verde", japaneseName: "カーボベルデ" },
    { code: "KH", name: "Cambodia", japaneseName: "カンボジア" },
    { code: "CM", name: "Cameroon", japaneseName: "カメルーン" },
    { code: "CA", name: "Canada", japaneseName: "カナダ" },
    { code: "CF", name: "Central African Republic", japaneseName: "中央アフリカ共和国" },
    { code: "TD", name: "Chad", japaneseName: "チャド" },
    { code: "CL", name: "Chile", japaneseName: "チリ" },
    { code: "CN", name: "China", japaneseName: "中国" },
    { code: "CO", name: "Colombia", japaneseName: "コロンビア" },
    { code: "KM", name: "Comoros", japaneseName: "コモロ" },
    { code: "CG", name: "Congo (Republic of the)", japaneseName: "コンゴ" },
    { code: "CR", name: "Costa Rica", japaneseName: "コスタリカ" },
    { code: "CI", name: "Cote d'Ivoire", japaneseName: "コートジボアール" },
    { code: "HR", name: "Croatia", japaneseName: "クロアチア" },
    { code: "CU", name: "Cuba", japaneseName: "キューバ" },
    { code: "CY", name: "Cyprus", japaneseName: "キプロス" },
    { code: "CZ", name: "Czech Republic", japaneseName: "チェコ" },
    { code: "KP", name: "Democratic People's Republic of Korea", japaneseName: "朝鮮民主主義人民共和国" },
    { code: "CD", name: "Democratic Republic of the Congo", japaneseName: "コンゴ民主共和国" },
    { code: "DK", name: "Denmark", japaneseName: "デンマーク" },
    { code: "DJ", name: "Djibouti", japaneseName: "ジブチ" },
    { code: "DM", name: "Dominica", japaneseName: "ドミニカ" },
    { code: "DO", name: "Dominican Republic", japaneseName: "ドミニカ共和国" },
    { code: "EC", name: "Ecuador", japaneseName: "エクアドル" },
    { code: "EG", name: "Egypt", japaneseName: "エジプト" },
    { code: "SV", name: "El Salvador", japaneseName: "エルサルバドル" },
    { code: "GQ", name: "Equatorial Guinea", japaneseName: "赤道ギニア" },
    { code: "ER", name: "Eritrea", japaneseName: "エリトリア" },
    { code: "EE", name: "Estonia", japaneseName: "エストニア" },
    { code: "SZ", name: "Eswatini", japaneseName: "エスワティニ" },
    { code: "ET", name: "Ethiopia", japaneseName: "エチオピア" },
    { code: "FJ", name: "Fiji", japaneseName: "フィジー" },
    { code: "FI", name: "Finland", japaneseName: "フィンランド" },
    { code: "FR", name: "France", japaneseName: "フランス" },
    { code: "GA", name: "Gabon", japaneseName: "ガボン" },
    { code: "GM", name: "Gambia", japaneseName: "ガンビア" },
    { code: "GE", name: "Georgia", japaneseName: "ジョージア" },
    { code: "DE", name: "Germany", japaneseName: "ドイツ" },
    { code: "GH", name: "Ghana", japaneseName: "ガーナ" },
    { code: "GR", name: "Greece", japaneseName: "ギリシャ" },
    { code: "GD", name: "Grenada", japaneseName: "グレナダ" },
    { code: "GT", name: "Guatemala", japaneseName: "グアテマラ" },
    { code: "GN", name: "Guinea", japaneseName: "ギニア" },
    { code: "GW", name: "Guinea-Bissau", japaneseName: "ギニアビサウ" },
    { code: "GY", name: "Guyana", japaneseName: "ガイアナ" },
    { code: "HT", name: "Haiti", japaneseName: "ハイチ" },
    { code: "HN", name: "Honduras", japaneseName: "ホンジュラス" },
    { code: "HU", name: "Hungary", japaneseName: "ハンガリー" },
    { code: "IS", name: "Iceland", japaneseName: "アイスランド" },
    { code: "IN", name: "India", japaneseName: "インド" },
    { code: "ID", name: "Indonesia", japaneseName: "インドネシア" },
    { code: "IR", name: "Iran", japaneseName: "イラン" },
    { code: "IQ", name: "Iraq", japaneseName: "イラク" },
    { code: "IE", name: "Ireland", japaneseName: "アイルランド" },
    { code: "IL", name: "Israel", japaneseName: "イスラエル" },
    { code: "IT", name: "Italy", japaneseName: "イタリア" },
    { code: "JM", name: "Jamaica", japaneseName: "ジャマイカ" },
    { code: "JP", name: "Japan", japaneseName: "日本" },
    { code: "JO", name: "Jordan", japaneseName: "ヨルダン" },
    { code: "KZ", name: "Kazakhstan", japaneseName: "カザフスタン" },
    { code: "KE", name: "Kenya", japaneseName: "ケニア" },
    { code: "KI", name: "Kiribati", japaneseName: "キリバス" },
    { code: "KW", name: "Kuwait", japaneseName: "クウェート" },
    { code: "KG", name: "Kyrgyzstan", japaneseName: "キルギスタン" },
    { code: "LA", name: "Lao People's Democratic Republic", japaneseName: "ラオス人民民主共和国" },
    { code: "LV", name: "Latvia", japaneseName: "ラトビア" },
    { code: "LB", name: "Lebanon", japaneseName: "レバノン" },
    { code: "LS", name: "Lesotho", japaneseName: "レソト" },
    { code: "LR", name: "Liberia", japaneseName: "リベリア" },
    { code: "LY", name: "Libya", japaneseName: "リビア" },
    { code: "LI", name: "Liechtenstein", japaneseName: "リヒテンシュタイン" },
    { code: "LT", name: "Lithuania", japaneseName: "リトアニア" },
    { code: "LU", name: "Luxembourg", japaneseName: "ルクセンブルク" },
    { code: "MG", name: "Madagascar", japaneseName: "マダガスカル" },
    { code: "MW", name: "Malawi", japaneseName: "マラウィ" },
    { code: "MY", name: "Malaysia", japaneseName: "マレーシア" },
    { code: "MV", name: "Maldives", japaneseName: "モルディブ" },
    { code: "ML", name: "Mali", japaneseName: "マリ" },
    { code: "MT", name: "Malta", japaneseName: "マルタ" },
    { code: "MH", name: "Marshall Islands", japaneseName: "マーシャル諸島" },
    { code: "MR", name: "Mauritania", japaneseName: "モーリタニア" },
    { code: "MU", name: "Mauritius", japaneseName: "モーリシャス" },
    { code: "MX", name: "Mexico", japaneseName: "メキシコ" },
    { code: "FM", name: "Micronesia (Federated States of)", japaneseName: "ミクロネシア連邦" },
    { code: "MC", name: "Monaco", japaneseName: "モナコ" },
    { code: "MN", name: "Mongolia", japaneseName: "モンゴル" },
    { code: "ME", name: "Montenegro", japaneseName: "モンテネグロ" },
    { code: "MA", name: "Morocco", japaneseName: "モロッコ" },
    { code: "MZ", name: "Mozambique", japaneseName: "モザンビーク" },
    { code: "MM", name: "Myanmar", japaneseName: "ミャンマー" },
    { code: "NA", name: "Namibia", japaneseName: "ナミビア" },
    { code: "NR", name: "Nauru", japaneseName: "ナウル" },
    { code: "NP", name: "Nepal", japaneseName: "ネパール" },
    { code: "NL", name: "Netherlands", japaneseName: "オランダ" },
    { code: "NZ", name: "New Zealand", japaneseName: "ニュージーランド" },
    { code: "NI", name: "Nicaragua", japaneseName: "ニカラグア" },
    { code: "NE", name: "Niger", japaneseName: "ニジェール" },
    { code: "NG", name: "Nigeria", japaneseName: "ナイジェリア" },
    { code: "MK", name: "North Macedonia", japaneseName: "北マケドニア" },
    { code: "NO", name: "Norway", japaneseName: "ノルウェー" },
    { code: "OM", name: "Oman", japaneseName: "オマーン" },
    { code: "PK", name: "Pakistan", japaneseName: "パキスタン" },
    { code: "PW", name: "Palau", japaneseName: "パラオ" },
    { code: "PA", name: "Panama", japaneseName: "パナマ" },
    { code: "PG", name: "Papua New Guinea", japaneseName: "パプア・ニューギニア" },
    { code: "PY", name: "Paraguay", japaneseName: "パラグアイ" },
    { code: "PE", name: "Peru", japaneseName: "ペルー" },
    { code: "PH", name: "Philippines", japaneseName: "フィリピン" },
    { code: "PL", name: "Poland", japaneseName: "ポーランド" },
    { code: "PT", name: "Portugal", japaneseName: "ポルトガル" },
    { code: "QA", name: "Qatar", japaneseName: "カタール" },
    { code: "KR", name: "Republic of Korea", japaneseName: "韓国" },
    { code: "MD", name: "Republic of Moldova", japaneseName: "モルドバ" },
    { code: "RO", name: "Romania", japaneseName: "ルーマニア" },
    { code: "RU", name: "Russian Federation", japaneseName: "ロシア連邦" },
    { code: "RW", name: "Rwanda", japaneseName: "ルワンダ" },
    { code: "KN", name: "Saint Kitts and Nevis", japaneseName: "セントクリストファー・ネイビス" },
    { code: "LC", name: "Saint Lucia", japaneseName: "セントルシア" },
    { code: "VC", name: "Saint Vincent and the Grenadines", japaneseName: "セントビンセントおよびグレナディーン諸島" },
    { code: "WS", name: "Samoa", japaneseName: "サモア" },
    { code: "SM", name: "San Marino", japaneseName: "サンマリノ" },
    { code: "ST", name: "Sao Tome and Principe", japaneseName: "サントメ・プリンシペ" },
    { code: "SA", name: "Saudi Arabia", japaneseName: "サウジアラビア" },
    { code: "SN", name: "Senegal", japaneseName: "セネガル" },
    { code: "RS", name: "Serbia", japaneseName: "セルビア" },
    { code: "SC", name: "Seychelles", japaneseName: "セイシェル" },
    { code: "SL", name: "Sierra Leone", japaneseName: "シエラレオネ" },
    { code: "SG", name: "Singapore", japaneseName: "シンガポール" },
    { code: "SK", name: "Slovakia", japaneseName: "スロバキア" },
    { code: "SI", name: "Slovenia", japaneseName: "スロベニア" },
    { code: "SB", name: "Solomon Islands", japaneseName: "ソロモン諸島" },
    { code: "SO", name: "Somalia", japaneseName: "ソマリア" },
    { code: "ZA", name: "South Africa", japaneseName: "南アフリカ" },
    { code: "SS", name: "South Sudan", japaneseName: "南スーダン" },
    { code: "ES", name: "Spain", japaneseName: "スペイン" },
    { code: "LK", name: "Sri Lanka", japaneseName: "スリランカ" },
    { code: "SD", name: "Sudan", japaneseName: "スーダン" },
    { code: "SR", name: "Suriname", japaneseName: "スリナム" },
    { code: "SE", name: "Sweden", japaneseName: "スウェーデン" },
    { code: "CH", name: "Switzerland", japaneseName: "スイス" },
    { code: "SY", name: "Syria", japaneseName: "シリア" },
    { code: "TJ", name: "Tajikistan", japaneseName: "タジキスタン" },
    { code: "TH", name: "Thailand", japaneseName: "タイ" },
    { code: "TL", name: "Timor-Leste", japaneseName: "東ティモール" },
    { code: "TG", name: "Togo", japaneseName: "トーゴ" },
    { code: "TO", name: "Tonga", japaneseName: "トンガ" },
    { code: "TT", name: "Trinidad and Tobago", japaneseName: "トリニダード・トバゴ" },
    { code: "TN", name: "Tunisia", japaneseName: "チュニジア" },
    { code: "TR", name: "Turkey", japaneseName: "トルコ" },
    { code: "TM", name: "Turkmenistan", japaneseName: "トルクメニスタン" },
    { code: "TV", name: "Tuvalu", japaneseName: "ツバル" },
    { code: "UG", name: "Uganda", japaneseName: "ウガンダ" },
    { code: "UA", name: "Ukraine", japaneseName: "ウクライナ" },
    { code: "AE", name: "United Arab Emirates", japaneseName: "アラブ首長国連邦" },
    { code: "GB", name: "United Kingdom", japaneseName: "英国" },
    { code: "TZ", name: "United Republic of Tanzania", japaneseName: "タンザニア" },
    { code: "US", name: "United States of America", japaneseName: "米国" },
    { code: "UY", name: "Uruguay", japaneseName: "ウルグアイ" },
    { code: "UZ", name: "Uzbekistan", japaneseName: "ウズベキスタン" },
    { code: "VU", name: "Vanuatu", japaneseName: "バヌアツ" },
    { code: "VE", name: "Venezuela", japaneseName: "ベネズエラ" },
    { code: "VN", name: "Viet Nam", japaneseName: "ベトナム" },
    { code: "YE", name: "Yemen", japaneseName: "イエメン" },
    { code: "ZM", name: "Zambia", japaneseName: "ザンビア" },
    { code: "ZW", name: "Zimbabwe", japaneseName: "ジンバブエ" },
  ].sort((a, b) => a.name.localeCompare(b.name))
  
  