apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: traubling-project
  namespace: argocd
spec:
  description: Traubling application project
  sourceRepos:
  - 'https://github.com/kaicyou2532/web_traubling.git'
  destinations:
  - namespace: traubling
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'networking.k8s.io'
    kind: Ingress
  namespaceResourceWhitelist:
  - group: ''
    kind: '*'
  - group: 'apps'
    kind: '*'
  - group: 'networking.k8s.io'
    kind: '*'
  roles:
  - name: developer
    description: Developer role for traubling project
    policies:
    - p, proj:traubling-project:developer, applications, *, traubling-project/*, allow
    - p, proj:traubling-project:developer, repositories, *, *, allow
    groups:
    - your-org:developers
